name: 'mediNote_dbt'
version: '1.0.0'
config-version: 2

profile: 'medinote'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to clean when `dbt clean` is run
  - "target"
  - "dbt_packages"
  - "dbt_modules"

models:
  mediNote_dbt:
    +materialized: view